### ISSUE TITLE
Integers are not roundtriped

### ISSUE THREAD

**Issue by oschwald** [sysread/TOML-Tiny#7] opened 2020-08-06 15:19 UTC
I noticed this when trying to upgrade from `TOML::Parser`. For instance:

```perl
to_toml(from_toml('port = 5432'))
```

produces `port="5432"`.

For us, this made parsing of the output fail in strongly typed languages.

We were able to workaround this with `inflate_integer => sub ($v) { $v + 0 }`, but it seems like something that should work by default.

**Comment by sysread** [comment] 2020-08-10 13:39
Investigating this now.

**Comment by sysread** [comment] 2020-08-10 15:23
The bug is caused by `TOML::Tiny`'s efforts at preserving large ints and floats. Coercing ints and floats to numbers while parsing will cause those numbers to be truncated to the max int/float values supported by the perl being used. Clearly, this is a bug and must be fixed, but I'm hesitant to silently truncate input and I would like to avoid imposing the use of `Math::Big(Int|Float)` on callers.

The only good option I can think of is for the parser to attempt to detect a big int/float and either warn or die if the caller has not specified a custom inflation routine to handle that case. Or, perhaps, in those cases, they are left as strings, perhaps after emitting a warning.

What are your thoughts?

**Comment by oschwald** [comment] 2020-08-10 17:42
I figured something like this was probably the underlying reason. Would it make sense to use `Math::BigInt`/`Math::BigFloat` only for values that are too big for an IV, UV, or NV? The modules are in core so it won't add additional non-core dependencies and the performance consequence would only be felt by those who actually need them.

**Comment by sysread** [comment] 2020-08-10 20:46
I've got a possible solution on a branch. It doesn't automatically convert to `Math::Big(Int|Float)`, but it does end up needing to use those to handle the case of scientific notation -> https://github.com/sysread/TOML-Tiny/compare/roundtrip#diff-cf65929a9202cd92c15fd582bcc9abb8

I'm open to the idea of simply imposing `Math::Big(Int|Float)` on large numbers. It seems like less surprising behavior than to return a string in those cases.

**Comment by oschwald** [comment] 2020-08-11 00:16
That certainly looks like an improvement. You could probably handle exponent values if you wanted to build in some knowledge of IEEE 754 floats, but keeping it simple makes sense to me.

The handling of TOML hexadecimal, octal, and binary integers seems like it would be a bit unfortunate as it leaves decoding them to the end user, but it is no worse than it is now.

**Comment by oschwald** [comment] 2020-08-11 00:17
I wonder if it would make sense to strip underscores when doing the comparison.

**Comment by sysread** [comment] 2020-08-11 12:49
Underscores are stripped in the [tokenizer](https://github.com/sysread/TOML-Tiny/blob/master/lib/TOML/Tiny/Tokenizer.pm#L174).

**Comment by sysread** [comment] 2020-08-11 15:53
I've merged the branch. Pending successful build on Travis CI, I'll cut a new version at `727af8a8f8da45c907fae1ac9753f7bf17d15c07` and upload to CPAN.

**Closed by sysread** 2020-08-11 15:53 UTC
Labels: bug

**Comment by oschwald** [comment] 2020-08-12 00:25
Thank you!
